apiVersion: v1
kind: ConfigMap
metadata:
  name: comprehend-processor-config
data:
  INPUT_PATH: "/data/raw_reviews.json"
  OUTPUT_PATH: "/data/comprehend_output.json"
  BATCH_SIZE: "25"
  S3_INPUT_BUCKET: "comprehend-pala3105-2026"                # Download input from here
  S3_INPUT_KEY: "results/raw_reviews.json"                   # Download this file
  S3_BUCKET: "comprehend-pala3105-2026"                      # Where to upload output
  S3_PREFIX: "comprehend-output/"                            # Where to upload output
  # S3_PUBLIC_READ: "false"
